// packages/solidjs2/src/components/show/ShowGroup.tsx
import { type Component, For, Show } from "solid-js";
import type { ShowFieldVM, ShowViewModel, FieldGroup } from "specloom";
import { ShowVM } from "specloom";
import { ShowField } from "./ShowField.jsx";

export interface ShowGroupProps {
  group?: FieldGroup;
  fields: ShowFieldVM[];
  vm: ShowViewModel;
}

export const ShowGroup: Component<ShowGroupProps> = (props) => {
  return (
    <div class="rounded-lg border border-border p-4">
      <Show when={props.group}>
        <h3 class="mb-4 text-lg font-semibold text-foreground">
          {props.group!.label}
        </h3>
      </Show>

      <dl class="grid grid-cols-1 gap-4 md:grid-cols-2">
        <For each={props.fields}>
          {(field) => (
            <ShowField
              field={field}
              value={ShowVM.value(props.vm, field.name)}
            />
          )}
        </For>
      </dl>
    </div>
  );
};

// packages/svelte/src/lib/components/show/ShowGroup.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { FieldGroup, ShowFieldVM } from "specloom";
  import { ShowVM } from "specloom";
  import { getShowContext } from "./context.svelte.js";
  import { cn } from "$lib/utils.js";
  import ShowField from "./ShowField.svelte";

  interface Props {
    group: FieldGroup;
    class?: string;
    children?: Snippet<[{ group: FieldGroup; fields: ShowFieldVM[] }]>;
  }

  let { group, class: className, children }: Props = $props();
  const ctx = getShowContext();
  const getVM = () => new ShowVM(ctx.vm);

  const groupFields = $derived(getVM().fieldsInGroup(group.id));
</script>

{#if children}
  {@render children({ group, fields: groupFields })}
{:else}
  <div class={cn("rounded-lg border p-4", className)}>
    <h3 class="mb-4 text-lg font-semibold">{group.label}</h3>
    <dl class="grid grid-cols-1 gap-4 md:grid-cols-2">
      {#each groupFields as field}
        <ShowField {field} />
      {/each}
    </dl>
  </div>
{/if}
