// packages/solidjs/src/components/show/ShowGroup.tsx
import { type Component, type JSX, For, Show } from "solid-js";
import type { ShowFieldVM, FieldGroup } from "specloom";
import { ShowVM } from "specloom";
import { useShow } from "./context.jsx";
import { ShowField } from "./ShowField.jsx";

export interface ShowGroupProps {
  group: FieldGroup;
  renderField?: (field: ShowFieldVM, value: unknown) => JSX.Element;
  class?: string;
}

/**
 * ShowGroup - 詳細ビューのフィールドグループ
 */
export const ShowGroup: Component<ShowGroupProps> = (props) => {
  const { vm } = useShow();

  const fields = () => ShowVM.fieldsInGroup(vm(), props.group.id);

  return (
    <div class={props.class ?? "rounded-lg border border-border p-4"}>
      <Show when={props.group.label}>
        <h3 class="mb-4 text-lg font-semibold text-foreground">
          {props.group.label}
        </h3>
      </Show>

      <dl class="grid grid-cols-1 gap-4 md:grid-cols-2">
        <For each={fields()}>
          {(field) => {
            const value = ShowVM.value(vm(), field.name);
            return (
              <Show
                when={props.renderField}
                fallback={<ShowField field={field} value={value} />}
              >
                {props.renderField!(field, value)}
              </Show>
            );
          }}
        </For>
      </dl>
    </div>
  );
};

// packages/svelte/src/lib/components/show/ShowGroup.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { FieldGroup, ShowFieldVM } from "specloom";
  import { ShowVM } from "specloom";
  import { getShowContext } from "./context.svelte.js";
  import { cn } from "$lib/utils.js";
  import ShowField from "./ShowField.svelte";

  interface Props {
    group: FieldGroup;
    class?: string;
    children?: Snippet<[{ group: FieldGroup; fields: ShowFieldVM[] }]>;
  }

  let { group, class: className, children }: Props = $props();
  const ctx = getShowContext();
  const getVM = () => new ShowVM(ctx.vm);

  const groupFields = $derived(getVM().fieldsInGroup(group.id));
</script>

{#if children}
  {@render children({ group, fields: groupFields })}
{:else}
  <div class={cn("rounded-lg border p-4", className)}>
    <h3 class="mb-4 text-lg font-semibold">{group.label}</h3>
    <dl class="grid grid-cols-1 gap-4 md:grid-cols-2">
      {#each groupFields as field}
        <ShowField {field} />
      {/each}
    </dl>
  </div>
{/if}
