// packages/svelte/src/lib/components/list/ListView.svelte
<script lang="ts">
  import type { ListViewModel } from "specloom";
  import type { Snippet } from "svelte";
  import { createListContext } from "./context.svelte.js";
  import * as Card from "$lib/components/ui/card/index.js";
  import { cn } from "$lib/utils.js";
  import ListToolbar from "./ListToolbar.svelte";
  import ListTable from "./ListTable.svelte";
  import ListPagination from "./ListPagination.svelte";
  import ListLoading from "./ListLoading.svelte";
  import ListError from "./ListError.svelte";
  import ListEmpty from "./ListEmpty.svelte";

  interface Props {
    vm: ListViewModel;
    onSort?: (field: string) => void;
    onSelect?: (rowId: string) => void;
    onSelectAll?: () => void;
    onAction?: (actionId: string, rowIds?: string[]) => void;
    onPageChange?: (page: number) => void;
    onRowClick?: (rowId: string) => void;
    class?: string;
    children?: Snippet;
  }

  let {
    vm,
    onSort,
    onSelect,
    onSelectAll,
    onAction,
    onPageChange,
    onRowClick,
    class: className,
    children,
  }: Props = $props();

  // Create context for child components
  // Wrap callbacks in closures to capture latest values (Svelte 5 reactivity)
  createListContext({
    vm: () => vm,
    onSort: (field) => onSort?.(field),
    onSelect: (rowId) => onSelect?.(rowId),
    onSelectAll: () => onSelectAll?.(),
    onAction: (actionId, rowIds) => onAction?.(actionId, rowIds),
    onPageChange: (page) => onPageChange?.(page),
    onRowClick: (rowId) => onRowClick?.(rowId),
  });
</script>

<Card.Root class={cn(className)}>
  {#if children}
    {@render children()}
  {:else}
    <ListToolbar />
    {#if vm.isLoading}
      <ListLoading />
    {:else if vm.error}
      <ListError />
    {:else if vm.rows.length === 0}
      <ListEmpty />
    {:else}
      <ListTable />
      {#if vm.pagination}
        <ListPagination />
      {/if}
    {/if}
  {/if}
</Card.Root>

// packages/solidjs/src/components/list/ListView.tsx
import { type Component, type JSX, children as resolveChildren, Show } from "solid-js";
import type { ListViewModel } from "specloom";
import { ListProvider } from "./context.jsx";
import { ListToolbar } from "./ListToolbar.jsx";
import { ListTable } from "./ListTable.jsx";
import { ListPagination } from "./ListPagination.jsx";
import { ListLoading } from "./ListLoading.jsx";
import { ListError } from "./ListError.jsx";
import { cardClasses } from "../ui/index.js";

export interface ListViewProps {
  vm: ListViewModel;
  onSort?: (field: string) => void;
  onSelect?: (rowId: string) => void;
  onSelectAll?: () => void;
  onAction?: (actionId: string, rowIds?: string[]) => void;
  onPageChange?: (page: number) => void;
  onRowClick?: (rowId: string) => void;
  class?: string;
  children?: JSX.Element;
}

/**
 * ListView - Headless + 組み立て式のリストビュー
 *
 * @example
 * // シンプルに使う（デフォルト構成）
 * <ListView vm={vm} onAction={handleAction} />
 *
 * @example
 * // カスタマイズする
 * <ListView vm={vm} onAction={handleAction}>
 *   <ListToolbar>
 *     <ListHeaderActions />
 *   </ListToolbar>
 *   <ListTable />
 *   <ListPagination />
 * </ListView>
 */
export const ListView: Component<ListViewProps> = (props) => {
  const resolved = resolveChildren(() => props.children);

  // children が指定されていない場合はデフォルト構成を使用
  const hasChildren = () => {
    const c = resolved();
    return c !== undefined && c !== null && (Array.isArray(c) ? c.length > 0 : true);
  };

  return (
    <ListProvider
      vm={props.vm}
      onSort={props.onSort}
      onSelect={props.onSelect}
      onSelectAll={props.onSelectAll}
      onAction={props.onAction}
      onPageChange={props.onPageChange}
      onRowClick={props.onRowClick}
    >
      <div class={cardClasses(props.class)}>
        <Show when={hasChildren()} fallback={<DefaultListContent />}>
          {resolved()}
        </Show>
      </div>
    </ListProvider>
  );
};

/**
 * デフォルトのリスト構成
 */
function DefaultListContent() {
  return (
    <>
      <ListToolbar />
      <ListLoading />
      <ListError />
      <ListTable />
      <ListPagination />
    </>
  );
}
