// packages/svelte/src/lib/components/show/ShowField.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { ShowFieldVM } from "specloom";
  import { ShowVM } from "specloom";
  import { getShowContext } from "./context.svelte.js";
  import { cn } from "$lib/utils.js";

  interface Props {
    field: ShowFieldVM;
    class?: string;
    children?: Snippet<[{ field: ShowFieldVM; value: unknown; formatted: string }]>;
  }

  let { field, class: className, children }: Props = $props();
  const ctx = getShowContext();

  const value = $derived(ShowVM.value(ctx.vm, field.name));
  const formatted = $derived(ShowVM.formatValue(field, value));
</script>

{#if children}
  {@render children({ field, value, formatted })}
{:else}
  <div class={cn("flex flex-col gap-1", className)}>
    <dt class="text-sm font-medium text-muted-foreground">{field.label}</dt>
    <dd class="text-base">{formatted}</dd>
  </div>
{/if}

// packages/solidjs/src/components/show/ShowField.tsx
import { type Component } from "solid-js";
import type { ShowFieldVM } from "specloom";
import { FieldDisplay } from "../shared/FieldDisplay.jsx";

export interface ShowFieldProps {
  field: ShowFieldVM;
  value: unknown;
  class?: string;
}

/**
 * ShowField - 詳細ビューの単一フィールド表示
 */
export const ShowField: Component<ShowFieldProps> = (props) => {
  return (
    <div class={props.class ?? "flex flex-col gap-1"}>
      <dt class="text-sm font-medium text-muted-foreground">
        {props.field.label}
      </dt>
      <dd class="text-base text-foreground">
        <FieldDisplay field={props.field} value={props.value} />
      </dd>
    </div>
  );
};
