// packages/solidjs/src/components/form/FormBody.tsx
import {
  type Component,
  type JSX,
  For,
  Show,
  children as resolveChildren,
} from "solid-js";
import type { FormFieldVM } from "specloom";
import { useForm } from "./context.jsx";
import { FormField } from "./FormField.jsx";
import { FormGroup } from "./FormGroup.jsx";

export interface FormBodyProps {
  class?: string;
  children?: JSX.Element | ((field: FormFieldVM) => JSX.Element);
}

/**
 * FormBody - フォームのフィールド部分
 */
export const FormBody: Component<FormBodyProps> = (props) => {
  const { loading, visibleFields, groups, vm, values, onChange } = useForm();

  const hasGroups = () => groups().length > 0;

  const renderField = () => {
    if (typeof props.children === "function") {
      return props.children;
    }
    return undefined;
  };

  return (
    <Show when={!loading()}>
      <div class={props.class ?? "p-6"}>
        <Show
          when={hasGroups()}
          fallback={
            <div class="space-y-6">
              <For each={visibleFields()}>
                {(field) => (
                  <Show
                    when={renderField()}
                    fallback={
                      <FormField field={field} value={values()[field.name]} />
                    }
                  >
                    {renderField()!(field)}
                  </Show>
                )}
              </For>
            </div>
          }
        >
          <div class="space-y-8">
            <For each={groups()}>
              {(group) => (
                <FormGroup
                  group={group}
                  fields={vm().fieldsInGroup(group.id)}
                  renderField={renderField()}
                />
              )}
            </For>
          </div>
        </Show>
      </div>
    </Show>
  );
};

// packages/svelte/src/lib/components/form/FormBody.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { FormFieldVM, FieldGroup } from "specloom";
  import { getFormContext } from "./context.svelte.js";
  import * as Card from "$lib/components/ui/card/index.js";
  import { cn } from "$lib/utils.js";
  import FormGroup from "./FormGroup.svelte";
  import FormField from "./FormField.svelte";

  interface Props {
    class?: string;
    children?: Snippet<[{ fields: FormFieldVM[]; groups: FieldGroup[] }]>;
  }

  let { class: className, children }: Props = $props();
  const ctx = getFormContext();
</script>

<Card.Content class={cn(className)}>
  {#if children}
    {@render children({ fields: ctx.visibleFields, groups: ctx.groups })}
  {:else if ctx.groups.length > 0}
    <div class="space-y-8">
      {#each ctx.groups as group}
        <FormGroup {group} />
      {/each}
    </div>
  {:else}
    <div class="space-y-6">
      {#each ctx.visibleFields as field}
        <FormField {field} />
      {/each}
    </div>
  {/if}
</Card.Content>
