// packages/solidjs/src/components/form/FormView.tsx
import {
  type Component,
  type JSX,
  children as resolveChildren,
  Show,
} from "solid-js";
import type { FormViewModel } from "specloom";
import { FormProvider, useForm } from "./context.jsx";
import type { RelationOption } from "../shared/FieldInput.jsx";
import { FormHeader } from "./FormHeader.jsx";
import { FormBody } from "./FormBody.jsx";
import { FormFooter } from "./FormFooter.jsx";
import { FormLoading } from "./FormLoading.jsx";
import { FormError } from "./FormError.jsx";
import { cardClasses } from "../ui/index.js";

export interface FormViewProps {
  vm: FormViewModel;
  onChange: (name: string, value: unknown) => void;
  onSubmit: () => void;
  onAction?: (actionId: string) => void;
  /** リレーションフィールドのオプション検索 */
  onOptionsSearch?: (resource: string, query: string) => Promise<RelationOption[]>;
  class?: string;
  children?: JSX.Element;
}

/**
 * FormView - Headless + 組み立て式のフォームビュー
 *
 * @example
 * // シンプルに使う（デフォルト構成）
 * <FormView vm={vm} onChange={handleChange} onSubmit={handleSubmit} />
 *
 * @example
 * // カスタマイズする
 * <FormView vm={vm} onChange={handleChange} onSubmit={handleSubmit}>
 *   <FormHeader />
 *   <FormBody>
 *     {(field) => <MyCustomField field={field} />}
 *   </FormBody>
 *   <FormFooter />
 * </FormView>
 */
export const FormView: Component<FormViewProps> = (props) => {
  const resolved = resolveChildren(() => props.children);

  const hasChildren = () => {
    const c = resolved();
    return (
      c !== undefined && c !== null && (Array.isArray(c) ? c.length > 0 : true)
    );
  };

  return (
    <FormProvider
      vm={props.vm}
      onChange={props.onChange}
      onSubmit={props.onSubmit}
      onAction={props.onAction}
      onOptionsSearch={props.onOptionsSearch}
    >
      <FormViewInner class={props.class} hasChildren={hasChildren}>
        <Show when={hasChildren()} fallback={<DefaultFormContent />}>
          {resolved()}
        </Show>
      </FormViewInner>
    </FormProvider>
  );
};

interface FormViewInnerProps {
  class?: string;
  hasChildren: () => boolean;
  children: JSX.Element;
}

const FormViewInner: Component<FormViewInnerProps> = (props) => {
  const { onSubmit, canSubmit } = useForm();

  const handleSubmit = (e: Event) => {
    e.preventDefault();
    if (canSubmit()) {
      onSubmit();
    }
  };

  return (
    <form onSubmit={handleSubmit} class={cardClasses(props.class)}>
      {props.children}
    </form>
  );
};

/**
 * デフォルトのフォーム構成
 */
function DefaultFormContent() {
  return (
    <>
      <FormHeader />
      <FormLoading />
      <FormError />
      <FormBody />
      <FormFooter />
    </>
  );
}

// packages/svelte/src/lib/components/form/FormView.svelte
<script lang="ts">
  import type { FormViewModel } from "specloom";
  import type { Snippet } from "svelte";
  import { createFormContext, type RelationOption } from "./context.svelte.js";
  import * as Card from "$lib/components/ui/card/index.js";
  import { cn } from "$lib/utils.js";
  import FormHeader from "./FormHeader.svelte";
  import FormBody from "./FormBody.svelte";
  import FormFooter from "./FormFooter.svelte";
  import FormActions from "./FormActions.svelte";
  import FormLoading from "./FormLoading.svelte";
  import FormError from "./FormError.svelte";

  interface Props {
    vm: FormViewModel;
    onChange?: (name: string, value: unknown) => void;
    onSubmit?: () => void;
    onAction?: (actionId: string) => void;
    onOptionsSearch?: (resource: string, query: string) => Promise<RelationOption[]>;
    /** Timezone for date/datetime formatting (e.g., 'Asia/Tokyo', 'UTC'). undefined = local time */
    timeZone?: string;
    class?: string;
    children?: Snippet;
  }

  let {
    vm,
    onChange = () => {},
    onSubmit = () => {},
    onAction,
    onOptionsSearch,
    timeZone,
    class: className,
    children,
  }: Props = $props();

  // Create context for child components
  // Wrap callbacks in closures to capture latest values (Svelte 5 reactivity)
  createFormContext({
    vm: () => vm,
    onChange: (name, value) => onChange(name, value),
    onSubmit: () => onSubmit(),
    onAction: (actionId) => onAction?.(actionId),
    onOptionsSearch: (resource, query) => onOptionsSearch?.(resource, query) ?? Promise.resolve([]),
    timeZone: () => timeZone,
  });

  function handleSubmit(e: Event) {
    e.preventDefault();
    onSubmit();
  }
</script>

<form onsubmit={handleSubmit}>
  <Card.Root class={cn(className)}>
    {#if children}
      {@render children()}
    {:else}
      <FormHeader>
        {#snippet children({ label })}
          <Card.Title>{label}</Card.Title>
          <FormActions />
        {/snippet}
      </FormHeader>
      {#if vm.isLoading}
        <FormLoading />
      {:else if vm.error}
        <FormError />
      {:else}
        <FormBody />
        <FormFooter />
      {/if}
    {/if}
  </Card.Root>
</form>
