// packages/svelte/src/lib/components/form/FormGroup.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { FieldGroup, FormFieldVM } from "specloom";
  import { FormHelpers } from "specloom";
  import { getFormContext } from "./context.svelte.js";
  import { cn } from "$lib/utils.js";
  import FormField from "./FormField.svelte";

  interface Props {
    group: FieldGroup;
    class?: string;
    children?: Snippet<[{ group: FieldGroup; fields: FormFieldVM[] }]>;
  }

  let { group, class: className, children }: Props = $props();
  const ctx = getFormContext();

  const groupFields = $derived(FormHelpers.fieldsInGroup(ctx.vm, group.id));
</script>

{#if children}
  {@render children({ group, fields: groupFields })}
{:else}
  <fieldset class={cn("rounded-lg border p-6", className)}>
    <legend class="px-2 text-sm font-semibold">{group.label}</legend>
    <div class="space-y-6">
      {#each groupFields as field}
        <FormField {field} />
      {/each}
    </div>
  </fieldset>
{/if}

// packages/solidjs2/src/components/form/FormGroup.tsx
import { type Component, For, Show } from "solid-js";
import type { FormFieldVM, FormViewModel, FieldGroup } from "specloom";
import { FormField } from "./FormField.jsx";

export interface FormGroupProps {
  group?: FieldGroup;
  fields: FormFieldVM[];
  vm: FormViewModel;
  values: Record<string, unknown>;
  onChange: (name: string, value: unknown) => void;
}

export const FormGroup: Component<FormGroupProps> = (props) => {
  return (
    <fieldset class="rounded-lg border border-border p-6">
      <Show when={props.group}>
        <legend class="px-2 text-sm font-semibold text-foreground">
          {props.group!.label}
        </legend>
      </Show>

      <div class="space-y-6">
        <For each={props.fields}>
          {(field) => (
            <FormField
              field={field}
              vm={props.vm}
              value={props.values[field.name]}
              onChange={props.onChange}
            />
          )}
        </For>
      </div>
    </fieldset>
  );
};
